Feature/add file location
sdm-lang/rust-sdml pull request #17
Opened 2024-12-30 20:52 UTC by mchaloupka

I have added the location in SDML file in the RDF output which is produced after the `generate` CLI command is called. I have done it using an additional macro which accesses the `span()` method on the given definition and writes out the location (if available).

To be able to do that, I also had to add the get/set methods for span on the definitions where it was not yet present. The field was always present already.

From usability perspective, I also added the logic to include also line and column in the source file as that tends to be more user friendly than bytes. The tree-sitter exposes that, but I had to change the `Span` definition to include this detailed information.

The lats part of this change was to update all the tests that use snapshots. It would be tedious to update them by hand, so I added the ability to update them automatically. The following command does not fail if the examples output files differ, it updates them instead:
```
UPDATE_EXAMPLES_OUTPUT=1 cargo test
```

_Disclaimer: the diff contains also https://github.com/sdm-lang/rust-sdml/pull/16 as that allows me to have working test._

2025-01-16 17:09 UTC, johnstonskj commented on sdml-core/src/model/definitions/classes.rs
> +    get_and_set!(pub span, set_span, unset_span => optional has_span, Span);
these are added via the `impl_has_source_span_for` macro which implements the `HasSourceSpan` trait. This trait names the field `source_span` and results in the methods `with_source_span`, `has_source_span`, `source_span`, `set_source_span`, and `unset_source_span`.

2025-01-16 17:10 UTC, johnstonskj commented on sdml-core/src/model/definitions/datatypes.rs
> +    get_and_set!(pub span, set_span, unset_span => optional has_span, Span);
see comment above.

2025-01-16 17:13 UTC, johnstonskj commented on sdml-core/src/model/definitions/classes.rs
> +    get_and_set!(pub span, set_span, unset_span => optional has_span, Span);
This is actually performed by the `impl_has_source_span_for` macro, which implements the  `crate::model::HasSourceSpan` trait resulting in the methods `with_source_span`, `has_source_span`, `source_span`, `set_source_span` and `unset_source_span`.

2025-01-16 17:13 UTC, johnstonskj commented on sdml-core/src/model/definitions/datatypes.rs
> +    get_and_set!(pub span, set_span, unset_span => optional has_span, Span);
see comment above re:`impl_has_source_span_for`.

2025-01-16 17:14 UTC, johnstonskj commented on sdml-core/src/model/definitions/entities.rs
> +    get_and_set!(pub span, set_span, unset_span => optional has_span, Span);
see comment above re:`impl_has_source_span_for`.

2025-01-16 17:14 UTC, johnstonskj commented on sdml-core/src/model/definitions/enums.rs
> +    get_and_set!(pub span, set_span, unset_span => optional has_span, Span);
see comment above re:`impl_has_source_span_for`.

2025-01-16 17:14 UTC, johnstonskj commented on sdml-core/src/model/definitions/enums.rs
> +    get_and_set!(pub span, set_span, unset_span => optional has_span, Span);
see comment above re:`impl_has_source_span_for`.

2025-01-16 17:14 UTC, johnstonskj commented on sdml-core/src/model/definitions/events.rs
> +    get_and_set!(pub span, set_span, unset_span => optional has_span, Span);
see comment above re:`impl_has_source_span_for`.

2025-01-16 17:14 UTC, johnstonskj commented on sdml-core/src/model/definitions/rdf.rs
> +    get_and_set!(pub span, set_span, unset_span => optional has_span, Span);
see comment above re:`impl_has_source_span_for`.

2025-01-16 17:14 UTC, johnstonskj commented on sdml-core/src/model/definitions/unions.rs
> +    get_and_set!(pub span, set_span, unset_span => optional has_span, Span);
see comment above re:`impl_has_source_span_for`.

2025-01-16 17:14 UTC, johnstonskj commented on sdml-core/src/model/definitions/unions.rs
> +    get_and_set!(pub span, set_span, unset_span => optional has_span, Span);
see comment above re:`impl_has_source_span_for`.

2025-01-16 17:15 UTC, johnstonskj commented on sdml-core/src/model/members/mod.rs
> +    get_and_set!(pub span, set_span, unset_span => optional has_span, Span);
see comment above re:`impl_has_source_span_for`.

2025-01-16 17:17 UTC, johnstonskj commented on sdml-core/src/model/modules.rs
> +    get_and_set!(pub span, set_span, unset_span => optional has_span, Span);
see comment above re:`impl_has_source_span_for`.

2025-01-16 17:24 UTC, johnstonskj requested changes
If you remove all the `get_and_set` macro calls you should be able to use the existing `source_span` instead of your `span` methods. If you make those changes I'll merge.

2025-01-22 00:41 UTC, mchaloupka commented on sdml-core/src/model/definitions/classes.rs
> +    get_and_set!(pub span, set_span, unset_span => optional has_span, Span);
Have not noticed that macro. What lead me in the wrong direction is that module actually had such `get_and_set` available. Will change it to use the existing macro as it seems to be implemented in all/most places I need.

2025-01-22 00:52 UTC, mchaloupka commented
> If you remove all the `get_and_set` macro calls you should be able to use the existing `source_span` instead of your `span` methods. If you make those changes I'll merge.

Done. Lmk if there is anything else.

2025-01-24 21:24 UTC, merged