Add the ability to provide SDML Catalog path via an environment variable
sdm-lang/rust-sdml pull request #18
Opened 2024-12-31 01:07 UTC by mchaloupka

This PR adds the ability to provide the path to SDML catalog via an environment variable. It just changes the implementation of the default resolver, so it either takes path from the environment variable if present or it looks in the current folder (and traverses through the parent folders).

I have added unit test that verifies this behavior. Have added dependency on `serial_test` as I need to ensure that the tests touching the environment variables are not running in parallel.

_Disclaimer: the diff contains also https://github.com/sdm-lang/rust-sdml/pull/16 as that allows me to have working tests._

2025-01-16 17:19 UTC, johnstonskj commented on sdml-parse/Cargo.toml
> +serial_test = "3.2.0"
Move this down to dev-dependencies

2025-01-16 17:20 UTC, johnstonskj commented on sdml-parse/src/load.rs
> +pub const SDML_CATALOG_FILE_VARIABLE: &str = "SDML_CATALOG";
I would make this `SDML_CATALOG_FILE`, seems easier to understand, and you named the constant `SDML_CATALOG_FILE_VARIABLE` after all.

2025-01-16 17:23 UTC, johnstonskj requested changes
Can you make the change to the Cargo.toml file and environment variable please and this should be an easy one.

2025-01-21 23:31 UTC, mchaloupka commented on sdml-parse/Cargo.toml
> +serial_test = "3.2.0"
Done.

2025-01-21 23:31 UTC, mchaloupka commented on sdml-parse/src/load.rs
> +pub const SDML_CATALOG_FILE_VARIABLE: &str = "SDML_CATALOG";
Makes sense. Updated.

2025-01-21 23:32 UTC, mchaloupka commented
> Can you make the change to the Cargo.toml file and environment variable please and this should be an easy one.

Done.

2025-01-24 21:23 UTC, merged